language: go
sudo: false
addons:
  apt:
    packages:
    - rpm
go:
- '1.4'
env:
  global:
    secure: COMQYKj9O6GUuoDRa5OVfOT8i4m1f/JDH6LaGLI8Nkb84oaq9fgvpjVMBgUcWbYT52UXt3NNy7N8B3d8VEmCHvBIjZh296OhHsAvFf9hvcjx5POjKXODV1rwdgtyYafaLUPllCBe/lLKn819ktD3PB1tjxQ0//r4APW82W4wpYs=
install:
- make deps
script:
- make lint
- make test
before_deploy:
- make toolchain
- make build
- make package
- make packagecloud
deploy:
  provider: releases
  api_key:
    secure: WBb1z0GV1uD8pB/UMDVqiqIFHcgxl2fngF9Qg8Obe0IJIuBN8ak4H1ulYKYcRgguJjefMG/OnPT2xHCsSme+OanxBcGDiYijG1vVmBqnMV8wTK5ulqkgSz7QVH4oCmdqd8WnHKqqqXmLUARRAUkvKFDCf2mq6qyAy+wKw7jPluI=
  file:
    - out/gitlab-ci-multi-runner-linux-arm
    - out/gitlab-ci-multi-runner-linux-386
    - out/gitlab-ci-multi-runner-linux-amd64
    - out/gitlab-ci-multi-runner-darwin-386
    - out/gitlab-ci-multi-runner-darwin-amd64
    - out/gitlab-ci-multi-runner-windows-386.exe
    - out/gitlab-ci-multi-runner-windows-amd64.exe
  on:
    repo: ayufan/gitlab-ci-multi-runner
    tags: true
